# Generated by Django 4.1.3 on 2022-12-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='sold_date',
            field=models.DateField(null=True),
        ),
    ]
