# Generated by Django 4.1.3 on 2022-12-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_productdata_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='datetime_stamp',
            field=models.DateField(),
        ),
    ]
