# Generated by Django 4.1.3 on 2022-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_productdata_datetime_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='test',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
