# Generated by Django 4.1.3 on 2022-12-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_productdata_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='test',
        ),
    ]
