# Generated by Django 4.1.3 on 2023-01-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_productdata_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='aggregate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
